### ISSUE TITLE
Remove table in "Appendix A"

### ISSUE THREAD

**Issue by lisaTeis** [secureCryptoConfig/secureCryptoConfig#9]
format and adapt content

**Comment by kmindi** [comment]
was ist hier die Aufgabe? Also wie entscheide ich ob das erledigt ist oder ob noch was zu tun ist?

**Comment by lisaTeis** [comment]
Ich hatte damals (vor ein paar Wochen bereits) die Tabelle in Appendix A Examples angepasst/mit Beispielen gefüllt. Damals hattest du noch nicht drüber geschaut. War nur als Erinnerung, dass du auch nochmal über die Tabelle schaust, ob sich die Vorschläge zum jeweiligen Use Case als sichere Beispiele eignen.

**Comment by kmindi** [comment]
Müssen pro Use case mindestens zwei verschiedene vorgeschlagene Algorithmen/Parameter Kombinationen sein, bitte noch mal aktualisieren/ergänzen

**Comment by kmindi** [comment]
@lisaTeis die Tabelle kann entfernt werden, wir brauchen erstmal nur die JSON-Datei in der das ja quasi genau so drinsteht. Um die Darstellung in einer Tabelle o.ä. kümmern wir uns später.
